### ISSUE TITLE
Update to latest jquery.browser

### ISSUE THREAD

**Issue by le717** [wymeditor/wymeditor#655]
I was alerted by @lehni to an issue in this project caused by the jQuery.browser plugin (gabceb/jquery-browser-plugin#35). This has been fixed in the latest 0.0.7 release. If it is still an issue, you will want to update your copy.

**Comment by mightyiam** [comment]
Thank you, @le717. I do see some improvement to be made in the few very important lines that use `jquery.browser` for the main browser detection thing.

**Comment by mightyiam** [comment]
Implemented in #662. Thank you, @le717.
