### ISSUE TITLE
Some recent parser tests fail in IE8

### ISSUE THREAD

**Issue by mightyiam** [wymeditor/wymeditor#685]
#666

**Comment by winhamwr** [comment]
Doh. Did we not test these in IE8 @jlward ?

**Comment by mightyiam** [comment]
In any case, these seem like pretty much meaningless attempts from IE8 to make our tests fail. An extra space here and there.

**Comment by mightyiam** [comment]
On it.

**Comment by winhamwr** [comment]
Let's just make the expected output different for IE8. It's not worth doing actual work to strip newlines in the parser unless the newlines alter some semantic meaning (like with the bogus trailing newlines in `li` elements inserted by IE).

**Comment by mightyiam** [comment]
This is actual output from IE8. It seems to provide the broken, unclosed tag HTML back at us:
![screenshot from 2015-03-06 17 44 52](https://cloud.githubusercontent.com/assets/635591/6528127/a07e4e6a-c428-11e4-8c1e-13bff02dbefd.png)

Besides being utterly strange to me (what kind of a design causes this?) it also has a quirk of effectively adding a newline after the AAA, which gets turned into a space at some point before the assertion.

What use does the newline in `<p>hello\nshahar</p>` have?

## Currently in WYMeditor in chromium:
![screenshot from 2015-03-06 19 57 38](https://cloud.githubusercontent.com/assets/635591/6530847/10e14cb6-c43d-11e4-98f0-7e1e395859cf.png)

## In IE8
![screenshot from 2015-03-06 20 17 46](https://cloud.githubusercontent.com/assets/635591/6530965/ecb2541a-c43d-11e4-8995-51143438afa3.png)

The two look the same in the editor but the output is different. Chrome outputs a newline and IE8 a space.

So newlines anywhere but in `pre` are replaced by spaces in the DOM but may be output as either newlines or spaces when requesting HTML.

A consistent policy should be declared on newlines, turning them into spaces by the parser.

The case of the missing tag in IE should be fixed in some way, ideally. But it may as well just be accepted, as you say.

**Comment by mightyiam** [comment]
Anyway, I'm unmarking as a regression because the failing tests are very minor.

**Comment by winhamwr** [comment]
![screenshot from 2015-03-06 17 44 52](https://cloud.githubusercontent.com/assets/635591/6528127/a07e4e6a-c428-11e4-8c1e-13bff02dbefd.png)

Crap. Does that mean that #666 broke the TD auto-closing behavior in IE8?

**Comment by mightyiam** [comment]
> Does that mean that #666 broke the TD auto-closing behavior in IE8?

No, actually. It means that IE8 is a bit insane on this issue.

Think about what is going on here. This string is returned from `wymeditor.rawHtml()`. This string has an unclosed tag.

This means that in IE8, if the input HTML has this missing closing tag—the output HTML from the created DOM will also have the same closing tag missing.

Read it again and tell me if it doesn't blow your mind that that is even possible. I don't even believe myself on this but look:

![screenshot from 2015-03-06 23 38 02](https://cloud.githubusercontent.com/assets/635591/6536864/dd69e1aa-c459-11e4-9cc8-158c283664a9.png)

**Comment by mightyiam** [comment]
Can be fixed by #688.
