### ISSUE TITLE
Travis builds are not showing up in GitHub

### ISSUE THREAD

**Issue by mightyiam** [wymeditor/wymeditor#687]

**Comment by mightyiam** [comment]
![screenshot from 2015-03-06 15 19 21](https://cloud.githubusercontent.com/assets/635591/6525935/963b07e0-c414-11e4-8c0a-4eeb87276006.png)
@winhamwr It seems that Travis doesn't recognize my wymeditor permissions.

**Comment by mightyiam** [comment]
Just works again.

**Comment by winhamwr** [comment]
I redid All The Things. hooray!
