### ISSUE TITLE
Undo/redo KB shorts trigger undo when outside of document

### ISSUE THREAD

**Issue by mightyiam** [wymeditor/wymeditor#700]
Our undo/redo keyboard shortcuts are bound on the document (or body, or something).

The native undo/redo functionality is triggered when using keyboard shortcuts outside of focus on that element.

This is bad.

It is best if we do not only overwrite the native action of undo/redo keyboard shortcuts but disable undo/redo in the designMode document altogether.

**Comment by winhamwr** [comment]
Do we have an undo icon in the default toolbar? I think we removed it in PolicyStat's version, because it was so broken with the browser's implementation.

**Comment by mightyiam** [comment]
We do have undo/redo icons in the default toolbar.
