### ISSUE TITLE
Outsource iframe resizing in seamless skin

### ISSUE THREAD

**Issue by mightyiam** [wymeditor/wymeditor#721]
To [this module, right here](https://github.com/davidjbradshaw/iframe-resizer).

**Comment by mightyiam** [comment]
But, first, #723.

**Comment by winhamwr** [comment]
> this module, right here.

Nice! I wish that existed when I wrote the seamless skin.

**Comment by winhamwr** [comment]
Also, moving to that library should not precede #710 or PolicyStat/PolicyStat#1976

There are 8 working days before the end of the month.

**Comment by mightyiam** [comment]
I think that this issue is null if we ever migrate to `contentEditable`.
