### ISSUE TITLE
Discussion of `.editor.prototype._exec`: `wym.selectedContainer()` returns `false` when there are >1 selected containers, and what holes it makes?

### ISSUE THREAD

**Issue by VINTproYKT** [wymeditor/wymeditor#752]
Let's dive into `.editor.prototype._exec`:

```javascript
WYMeditor.editor.prototype._exec = function (cmd, param) {
    var wym = this,
        $span;

    if (typeof cmd !== "string") {
        throw "`_exec` expected a String `cmd`";
    }

    if (param && typeof param !== "string") {
        throw "`_exec` expected a String `param`";
    }

    if (wym.selectedContainer() === false) {
        return false;
    }

    if (
        wym.selectedContainer() === wym.body() &&
        // These are the two commands that are allowed directly in the body.
        cmd !== WYMeditor.EXEC_COMMANDS.INSERT_IMAGE &&
        cmd !== WYMeditor.EXEC_COMMANDS.FORMAT_BLOCK
    ) {
        return false;
    }

    wym._doc.execCommand(cmd, false, param);

    $span = jQuery(wym.selectedContainer()).filter("span").not("[id]");
    if ($span.length === 0) {
        return true;
    }
    if (
        $span.attr("class") === "" &&
        $span.attr("style") === "font-weight: normal;" ||
        $span.attr("class").toLowerCase() === "apple-style-span"
    ) {
        // An undesireable `span` was created. WebKit & Blink do this.
        $span.contents().unwrap();
    }

    return true;
};
```

Line 593 of `editor/base.js`:

```
    if (wym.selectedContainer() === false) {
```

This is what prevents multiparagraph selection.

When you remove this condition-statement, all works like a sharm: you just can select some text in 2 or more paragraphs and bold, emphasisize it.

May I ask: for what you need `.selectedContainer()` (except line 598)? Is it actually preventing new errors (when you're comparing with `false`), or it's in build stage still? Thanks!

**Comment by VINTproYKT** [comment]
However, I see that inline tags are wrapped rightly between paragraphs. Wow!
![image](https://cloud.githubusercontent.com/assets/5708819/10364028/235a0ff8-6df3-11e5-9e4b-570829b24fd0.png)

**Comment by winhamwr** [comment]
Hi Rodion,

I think the issue you're referring to was fixed with #741, right? [in master](https://github.com/wymeditor/wymeditor/blob/master/src/wymeditor/editor/base.js#L592), that line no longer exists.

Thanks
-Wes

**Comment by VINTproYKT** [comment]
@winhamwr It's strange. I have downloaded 1.0.8 milestone recently and spotted this line both in `jquery.wymeditor.js` and `src/wymeditor/editor/base.js`.

**Comment by mightyiam** [comment]
#741 did fix this issue. Please comment if I'm wrong.

**Comment by mightyiam** [comment]
And FYI, @VINTproYKT, the fact that you can select across elements and the bold command works, is not to be accredited to WYMeditor at all. It is all done by the browser, using the [`document.execCommand` API](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand), which is provided by the browsers. So that logic is implemented in each of the browses.

So, whether it does what you expect, or something entirely undesirable, it is the browser itself.
