### ISSUE TITLE
Q: Is this project active?

### ISSUE THREAD

**Issue by RafaelLinux** [wymeditor/wymeditor#791]
I'm interested in this project, but seems to be abandoned .... am I wrong?

Thank you

**Comment by matthijskooijman** [comment]
We're still happy users of this project at https://github.com/PlanBCode/hypha, but it seems all development halted so far. Looking through the [network graph](https://github.com/wymeditor/wymeditoa/network) there are also no forks that have seen more recent developments. We happened to be considering some improvements today, so maybe we will make a fork for our own purposes with some improvements...

@mightyiam, @winhamwr, @caffodian, you seem to be recent committers to this repo, are you still using WymEditor anywhere?

**Comment by mightyiam** [comment]
@matthijskooijman I learned JavaScript and the DOM working on this project years ago. This project is a "dinosaur". I would recommend searching for a modern alternative. I don't happen to know of one, but I'm certain there are some reasonable choices out there.
